### Baseline Characteristics

Baseline characteristics are summarised and tabulated below for each of the Primary Treatment Groups.

#### Age
```{r baseline_summary_demographics_age, echo = FALSE, cache = FALSE, fig.width = 8, fig.height = 8,eval = TRUE}
## Generate plots of Age at Baseline
age_gap %>%
    ## Filter Baseline group, with primary_treatment defined and without missing or zero age
    dplyr::filter(event_name == "Baseline") %>%
    dplyr::filter(!is.na(primary_treatment)) %>%
    dplyr::filter(age_exact != 0 & !is.na(age_exact)) %>%
    mutate(`Primary Treatment` = primary_treatment) %>%
    ## Histograms by treatment group
    ggplot(aes(age_exact, fill = `Primary Treatment`)) +
    geom_histogram(bins = 60) +
    xlab("Age (Years)") +
    ylab("N") +
    ggtitle(label = "Age distribution by Primary Treatment Group",
            subtitle = "Y-axis varies between plots") +
    facet_wrap(~primary_treatment, ncol = 1, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "none")
## Table of summary statistics

```

#### EQ5D
```{r baseline_summary_demographics_eq5d, echo = FALSE, cache = FALSE, fig.width = 8, fig.height = 8,eval = TRUE}
## Generate plots of EQ5D at Baseline...
##
## Histograms by treatment group
age_gap %>%
    ## Filter Baseline group, with primary_treatment defined and without missing or zero age
    dplyr::filter(event_name == "Baseline") %>%
    dplyr::filter(!is.na(primary_treatment)) %>%
    dplyr::filter(!is.na(eq5d_score)) %>%
    ggplot(aes(eq5d_score, fill = primary_treatment)) +
    geom_histogram(bins = 60) +
    xlab("EQ5D Score") +
    ylab("N") +
    ggtitle(label = "EQ5D Score by Primary Treatment Group",
            subtitle = "Y-axis varies between plots") +
    facet_wrap(~primary_treatment, ncol = 1, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "none")
## Subset, reshape and tidy questionnaire responses...
eq5d <- age_gap %>%
        ## Filter Baseline group, with primary_treatment defined and without missing or zero age
        dplyr::filter(event_name == "Baseline") %>%
        dplyr::filter(!is.na(primary_treatment)) %>%
        dplyr::filter(!is.na(eq5d_score)) %>%
        ungroup() %>%
        dplyr::select(individual_id,
                      primary_treatment,
                      event_name,
                      mobility,
                      self_care,
                      usual_activity,
                      pain_discomfort,
                      anxiety_depression) %>%
        ## Reshape the data, replace variable names with neater descriptions and plot
        gather(key = key, value = Response, -individual_id, -primary_treatment, -event_name) %>%
        mutate(key   = case_when(key == "anxiety_depression" ~ "Anxiety / Depression",
                                 key == "mobility"           ~ "Mobility",
                                 key == "pain_discomfort"    ~ "Pain / Discomfort",
                                 key == "self_care"          ~ "Self Care",
                                 key == "usual_activity"     ~ "Usual Activity")) %>%
        unique()
## Stacked bar-chart of domain responses using base ggplo2
ggplot(eq5d, aes(x = primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle("EQ5D Domains at Baseline by Primary Treatment") +
    facet_grid(~key) +
    theme_bw()
## Same graphs using sjPlot::sjp.stackfrq(), plot by each treatment.
## To combine use something like cow_plot::plot_grid() / sjPlot::plot_grid() /
## patchwork (see https://github.com/thomasp85/patchwork)
eq5d_levels <- c('None', 'Slight', 'Moderate', 'Severe', 'Extreme')
eq5d_adjuvant <- dplyr::filter(eq5d, primary_treatment == "Adjuvant Endocrine") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(`Anxiety / Depression` = factor(`Anxiety / Depression`, levels = eq5d_levels),
                         `Mobility`            = factor(`Mobility`, levels = eq5d_levels),
                         `Pain / Discomfort`   = factor(`Pain / Discomfort`, levels = eq5d_levels),
                         `Self Care`           = factor(`Self Care`, levels = eq5d_levels),
                         `Usual Activity`      = factor(`Usual Activity`, levels = eq5d_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Adjuvant Endocrine",
                              prnt.plot = FALSE)
eq5d_chemotherapy <- dplyr::filter(eq5d, primary_treatment == "Chemotherapy") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(`Anxiety / Depression` = factor(`Anxiety / Depression`, levels = eq5d_levels),
                         `Mobility`            = factor(`Mobility`, levels = eq5d_levels),
                         `Pain / Discomfort`   = factor(`Pain / Discomfort`, levels = eq5d_levels),
                         `Self Care`           = factor(`Self Care`, levels = eq5d_levels),
                         `Usual Activity`      = factor(`Usual Activity`, levels = eq5d_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Chemotherapy",
                              prnt.plot = FALSE)
eq5d_primary <- dplyr::filter(eq5d, primary_treatment == "Primary Endocrine") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(`Anxiety / Depression` = factor(`Anxiety / Depression`, levels = eq5d_levels),
                         `Mobility`            = factor(`Mobility`, levels = eq5d_levels),
                         `Pain / Discomfort`   = factor(`Pain / Discomfort`, levels = eq5d_levels),
                         `Self Care`           = factor(`Self Care`, levels = eq5d_levels),
                         `Usual Activity`      = factor(`Usual Activity`, levels = eq5d_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Primary Endocrine",
                              prnt.plot = FALSE)
eq5d_radiotherapy <- dplyr::filter(eq5d, primary_treatment == "Radiotherapy") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(`Anxiety / Depression` = factor(`Anxiety / Depression`, levels = eq5d_levels),
                         `Mobility`            = factor(`Mobility`, levels = eq5d_levels),
                         `Pain / Discomfort`   = factor(`Pain / Discomfort`, levels = eq5d_levels),
                         `Self Care`           = factor(`Self Care`, levels = eq5d_levels),
                         `Usual Activity`      = factor(`Usual Activity`, levels = eq5d_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Radiotherapy",
                              prnt.plot = FALSE)
eq5d_surgery <- dplyr::filter(eq5d, primary_treatment == "Surgery") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(`Anxiety / Depression` = factor(`Anxiety / Depression`, levels = eq5d_levels),
                         `Mobility`            = factor(`Mobility`, levels = eq5d_levels),
                         `Pain / Discomfort`   = factor(`Pain / Discomfort`, levels = eq5d_levels),
                         `Self Care`           = factor(`Self Care`, levels = eq5d_levels),
                         `Usual Activity`      = factor(`Usual Activity`, levels = eq5d_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Surgery",
                              prnt.plot = FALSE)
eq5d_adjuvant$plot
eq5d_primary$plot
eq5d_chemotherapy$plot
eq5d_radiotherapy$plot
eq5d_surgery$plot

```

#### EORTC QLQ C30
```{r baseline_summary_demographics_c30, echo = FALSE, cache = FALSE, fig.width = 8, fig.height = 8,eval = TRUE}
## Generate plots of EORTC QLQ C30 at Baseline...
##
## Histograms of scaled scores by treatment group
age_gap %>%
    ## Filter Baseline group, with primary_treatment defined and without missing or zero age
    dplyr::filter(event_name == "Baseline") %>%
    dplyr::filter(!is.na(primary_treatment)) %>%
    dplyr::select(individual_id,
                  primary_treatment,
                  ql_scale,
                  pf_scale,
                  rf_scale,
                  ef_scale,
                  cf_scale,
                  sf_scale,
                  fa_scale,
                  nv_scale,
                  pa_scale,
                  dy_scale,
                  sl_scale,
                  ap_scale,
                  co_scale,
                  di_scale,
                  fi_scale) %>%
    gather(key   = Scale, value = value, -individual_id, -primary_treatment) %>%
    dplyr::filter(!is.na(value)) %>%
    mutate(Scale = gsub("_scale", "", Scale)) %>%
    unique() %>%
    ggplot(aes(value, fill = primary_treatment)) +
    geom_histogram(bins = 60) +
    xlab("EORTC QLQ C30") +
    ylab("N") +
    ggtitle(label = "EORTC QLQ C30 Scaled Scores by Primary Treatment Group",
            subtitle = "Y-axis varies between plots") +
    facet_grid(Scale~primary_treatment, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "none")
## Subset, reshape and tidy questionnaire responses...
c30 <- age_gap %>%
        ## Filter Baseline group, with primary_treatment defined and without missing or zero age
        dplyr::filter(event_name == "Baseline") %>%
        dplyr::filter(!is.na(primary_treatment)) %>%
        ungroup() %>%
        dplyr::select(individual_id,
                      primary_treatment,
                      event_name,
                      c30_q1, c30_q2, c30_q3, c30_q4, c30_q5,
                      c30_q6, c30_q7, c30_q8, c30_q9, c30_q10,
                      c30_q11, c30_q12, c30_q13, c30_q14, c30_q15,
                      c30_q16, c30_q17, c30_q18, c30_q19, c30_q20,
                      c30_q21, c30_q22, c30_q23, c30_q24, c30_q25,
                      c30_q26, c30_q27, c30_q28) %>%
        ## Reshape the data, replace variable names with neater descriptions and plot
        gather(key = key, value = Response, -individual_id, -primary_treatment, -event_name) %>%
        mutate(Response = factor(Response, levels = c("Not at All", "A Little", "Quite a Bit", "Very Much"))) %>%
        ## Optionally remove NAs, simply place '## dplyr...' if you wish to include NAs
        dplyr::filter(!is.na(Response)) %>%
        unique()
## Stacked bar-chart of domain responses using base ggplo2
ggplot(c30, aes(x = key, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "EORTC QLQ C30 Domains at Baseline by Primary Treatment",
            subtitle = "Excludes Missing Responses") +
    facet_grid(~primary_treatment) +
    theme_bw()
## Same graphs using sjPlot::sjp.stackfrq(), plot by each treatment.
## To combine use something like cow_plot::plot_grid() / sjPlot::plot_grid() /
## patchwork (see https://github.com/thomasp85/patchwork)
c30_levels <- c("Not at All", "A Little", "Quite a Bit", "Very Much")
c30_adjuvant <- dplyr::filter(c30, primary_treatment == "Adjuvant Endocrine") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(c30_q1  = factor(c30_q1,  levels = c30_levels),
                        c30_q2  = factor(c30_q2,  levels = c30_levels),
                        c30_q3  = factor(c30_q3,  levels = c30_levels),
                        c30_q4  = factor(c30_q4,  levels = c30_levels),
                        c30_q5  = factor(c30_q5,  levels = c30_levels),
                        c30_q6  = factor(c30_q6,  levels = c30_levels),
                        c30_q7  = factor(c30_q7,  levels = c30_levels),
                        c30_q8  = factor(c30_q8,  levels = c30_levels),
                        c30_q9  = factor(c30_q9,  levels = c30_levels),
                        c30_q10 = factor(c30_q10, levels = c30_levels),
                        c30_q11 = factor(c30_q11, levels = c30_levels),
                        c30_q12 = factor(c30_q12, levels = c30_levels),
                        c30_q13 = factor(c30_q13, levels = c30_levels),
                        c30_q14 = factor(c30_q14, levels = c30_levels),
                        c30_q15 = factor(c30_q15, levels = c30_levels),
                        c30_q16 = factor(c30_q16, levels = c30_levels),
                        c30_q17 = factor(c30_q17, levels = c30_levels),
                        c30_q18 = factor(c30_q18, levels = c30_levels),
                        c30_q19 = factor(c30_q19, levels = c30_levels),
                        c30_q20 = factor(c30_q20, levels = c30_levels),
                        c30_q21 = factor(c30_q21, levels = c30_levels),
                        c30_q22 = factor(c30_q22, levels = c30_levels),
                        c30_q23 = factor(c30_q23, levels = c30_levels),
                        c30_q24 = factor(c30_q24, levels = c30_levels),
                        c30_q25 = factor(c30_q25, levels = c30_levels),
                        c30_q26 = factor(c30_q26, levels = c30_levels),
                        c30_q27 = factor(c30_q27, levels = c30_levels),
                        c30_q28 = factor(c30_q28, levels = c30_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Adjuvant Endocrine",
                              prnt.plot = FALSE)
c30_primary <- dplyr::filter(c30, primary_treatment == "Primary Endocrine") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(c30_q1  = factor(c30_q1,  levels = c30_levels),
                        c30_q2  = factor(c30_q2,  levels = c30_levels),
                        c30_q3  = factor(c30_q3,  levels = c30_levels),
                        c30_q4  = factor(c30_q4,  levels = c30_levels),
                        c30_q5  = factor(c30_q5,  levels = c30_levels),
                        c30_q6  = factor(c30_q6,  levels = c30_levels),
                        c30_q7  = factor(c30_q7,  levels = c30_levels),
                        c30_q8  = factor(c30_q8,  levels = c30_levels),
                        c30_q9  = factor(c30_q9,  levels = c30_levels),
                        c30_q10 = factor(c30_q10, levels = c30_levels),
                        c30_q11 = factor(c30_q11, levels = c30_levels),
                        c30_q12 = factor(c30_q12, levels = c30_levels),
                        c30_q13 = factor(c30_q13, levels = c30_levels),
                        c30_q14 = factor(c30_q14, levels = c30_levels),
                        c30_q15 = factor(c30_q15, levels = c30_levels),
                        c30_q16 = factor(c30_q16, levels = c30_levels),
                        c30_q17 = factor(c30_q17, levels = c30_levels),
                        c30_q18 = factor(c30_q18, levels = c30_levels),
                        c30_q19 = factor(c30_q19, levels = c30_levels),
                        c30_q20 = factor(c30_q20, levels = c30_levels),
                        c30_q21 = factor(c30_q21, levels = c30_levels),
                        c30_q22 = factor(c30_q22, levels = c30_levels),
                        c30_q23 = factor(c30_q23, levels = c30_levels),
                        c30_q24 = factor(c30_q24, levels = c30_levels),
                        c30_q25 = factor(c30_q25, levels = c30_levels),
                        c30_q26 = factor(c30_q26, levels = c30_levels),
                        c30_q27 = factor(c30_q27, levels = c30_levels),
                        c30_q28 = factor(c30_q28, levels = c30_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Primary Endocrine",
                              prnt.plot = FALSE)
c30_chemotherapy <- dplyr::filter(c30, primary_treatment == "Chemotherapy") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(c30_q1  = factor(c30_q1,  levels = c30_levels),
                        c30_q2  = factor(c30_q2,  levels = c30_levels),
                        c30_q3  = factor(c30_q3,  levels = c30_levels),
                        c30_q4  = factor(c30_q4,  levels = c30_levels),
                        c30_q5  = factor(c30_q5,  levels = c30_levels),
                        c30_q6  = factor(c30_q6,  levels = c30_levels),
                        c30_q7  = factor(c30_q7,  levels = c30_levels),
                        c30_q8  = factor(c30_q8,  levels = c30_levels),
                        c30_q9  = factor(c30_q9,  levels = c30_levels),
                        c30_q10 = factor(c30_q10, levels = c30_levels),
                        c30_q11 = factor(c30_q11, levels = c30_levels),
                        c30_q12 = factor(c30_q12, levels = c30_levels),
                        c30_q13 = factor(c30_q13, levels = c30_levels),
                        c30_q14 = factor(c30_q14, levels = c30_levels),
                        c30_q15 = factor(c30_q15, levels = c30_levels),
                        c30_q16 = factor(c30_q16, levels = c30_levels),
                        c30_q17 = factor(c30_q17, levels = c30_levels),
                        c30_q18 = factor(c30_q18, levels = c30_levels),
                        c30_q19 = factor(c30_q19, levels = c30_levels),
                        c30_q20 = factor(c30_q20, levels = c30_levels),
                        c30_q21 = factor(c30_q21, levels = c30_levels),
                        c30_q22 = factor(c30_q22, levels = c30_levels),
                        c30_q23 = factor(c30_q23, levels = c30_levels),
                        c30_q24 = factor(c30_q24, levels = c30_levels),
                        c30_q25 = factor(c30_q25, levels = c30_levels),
                        c30_q26 = factor(c30_q26, levels = c30_levels),
                        c30_q27 = factor(c30_q27, levels = c30_levels),
                        c30_q28 = factor(c30_q28, levels = c30_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Chemotherapy",
                              prnt.plot = FALSE)
c30_radiotherapy <- dplyr::filter(c30, primary_treatment == "Radiotherapy") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(c30_q1  = factor(c30_q1,  levels = c30_levels),
                        c30_q2  = factor(c30_q2,  levels = c30_levels),
                        c30_q3  = factor(c30_q3,  levels = c30_levels),
                        c30_q4  = factor(c30_q4,  levels = c30_levels),
                        c30_q5  = factor(c30_q5,  levels = c30_levels),
                        c30_q6  = factor(c30_q6,  levels = c30_levels),
                        c30_q7  = factor(c30_q7,  levels = c30_levels),
                        c30_q8  = factor(c30_q8,  levels = c30_levels),
                        c30_q9  = factor(c30_q9,  levels = c30_levels),
                        c30_q10 = factor(c30_q10, levels = c30_levels),
                        c30_q11 = factor(c30_q11, levels = c30_levels),
                        c30_q12 = factor(c30_q12, levels = c30_levels),
                        c30_q13 = factor(c30_q13, levels = c30_levels),
                        c30_q14 = factor(c30_q14, levels = c30_levels),
                        c30_q15 = factor(c30_q15, levels = c30_levels),
                        c30_q16 = factor(c30_q16, levels = c30_levels),
                        c30_q17 = factor(c30_q17, levels = c30_levels),
                        c30_q18 = factor(c30_q18, levels = c30_levels),
                        c30_q19 = factor(c30_q19, levels = c30_levels),
                        c30_q20 = factor(c30_q20, levels = c30_levels),
                        c30_q21 = factor(c30_q21, levels = c30_levels),
                        c30_q22 = factor(c30_q22, levels = c30_levels),
                        c30_q23 = factor(c30_q23, levels = c30_levels),
                        c30_q24 = factor(c30_q24, levels = c30_levels),
                        c30_q25 = factor(c30_q25, levels = c30_levels),
                        c30_q26 = factor(c30_q26, levels = c30_levels),
                        c30_q27 = factor(c30_q27, levels = c30_levels),
                        c30_q28 = factor(c30_q28, levels = c30_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Radiotherapy",
                              prnt.plot = FALSE)
c30_surgery <- dplyr::filter(c30, primary_treatment == "Surgery") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(c30_q1  = factor(c30_q1,  levels = c30_levels),
                        c30_q2  = factor(c30_q2,  levels = c30_levels),
                        c30_q3  = factor(c30_q3,  levels = c30_levels),
                        c30_q4  = factor(c30_q4,  levels = c30_levels),
                        c30_q5  = factor(c30_q5,  levels = c30_levels),
                        c30_q6  = factor(c30_q6,  levels = c30_levels),
                        c30_q7  = factor(c30_q7,  levels = c30_levels),
                        c30_q8  = factor(c30_q8,  levels = c30_levels),
                        c30_q9  = factor(c30_q9,  levels = c30_levels),
                        c30_q10 = factor(c30_q10, levels = c30_levels),
                        c30_q11 = factor(c30_q11, levels = c30_levels),
                        c30_q12 = factor(c30_q12, levels = c30_levels),
                        c30_q13 = factor(c30_q13, levels = c30_levels),
                        c30_q14 = factor(c30_q14, levels = c30_levels),
                        c30_q15 = factor(c30_q15, levels = c30_levels),
                        c30_q16 = factor(c30_q16, levels = c30_levels),
                        c30_q17 = factor(c30_q17, levels = c30_levels),
                        c30_q18 = factor(c30_q18, levels = c30_levels),
                        c30_q19 = factor(c30_q19, levels = c30_levels),
                        c30_q20 = factor(c30_q20, levels = c30_levels),
                        c30_q21 = factor(c30_q21, levels = c30_levels),
                        c30_q22 = factor(c30_q22, levels = c30_levels),
                        c30_q23 = factor(c30_q23, levels = c30_levels),
                        c30_q24 = factor(c30_q24, levels = c30_levels),
                        c30_q25 = factor(c30_q25, levels = c30_levels),
                        c30_q26 = factor(c30_q26, levels = c30_levels),
                        c30_q27 = factor(c30_q27, levels = c30_levels),
                        c30_q28 = factor(c30_q28, levels = c30_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Surgery",
                              prnt.plot = FALSE)
c30_adjuvant$plot
c30_primary$plot
c30_chemotherapy$plot
c30_radiotherapy$plot
c30_surgery$plot

```

#### EORTC QLQ BR23
```{r baseline_summary_demographics_br23, echo = FALSE, cache = FALSE, fig.width = 8, fig.height = 8,eval = TRUE}
## Generate plots of BR23 at Baseline...
##
## Histograms of scaled scores by treatment group
age_gap %>%
    ## Filter Baseline group, with primary_treatment defined and without missing or zero age
    dplyr::filter(event_name == "Baseline") %>%
    dplyr::filter(!is.na(primary_treatment)) %>%
    dplyr::select(individual_id,
                  primary_treatment,
                  brbi_scale,
                  brsef_scale,
                  brfu_scale,
                  brst_scale,
                  brbs_scale,
                  bras_scale,
                  brhl_scale) %>%
    gather(key   = Scale, value = value, -individual_id, -primary_treatment) %>%
    dplyr::filter(!is.na(value)) %>%
    mutate(Scale = gsub("_scale", "", Scale)) %>%
    unique() %>%
    ggplot(aes(value, fill = primary_treatment)) +
    geom_histogram(bins = 60) +
    xlab("EORTC QLQ BR23") +
    ylab("N") +
    ggtitle(label = "EORTC QLQ BR23 Scaled Scores by Primary Treatment Group",
            subtitle = "Y-axis varies between plots") +
    facet_grid(Scale~primary_treatment, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "none")
## Subset, reshape and tidy questionnaire responses...
br23 <- age_gap %>%
        ## Filter Baseline group, with primary_treatment defined and without missing or zero age
        dplyr::filter(event_name == "Baseline") %>%
        dplyr::filter(!is.na(primary_treatment)) %>%
        ungroup() %>%
        dplyr::select(individual_id,
                      primary_treatment,
                      event_name,
                      br23_q31, br23_q32, br23_q33, br23_q34, br23_q35,
                      br23_q36, br23_q37, br23_q38, br23_q39, br23_q40,
                      br23_q41, br23_q42, br23_q43, br23_q44, br23_q45,
                      br23_q46, br23_q47, br23_q48, br23_q49, br23_q50,
                      br23_q51, br23_q52, br23_q53) %>%
        ## Reshape the data, replace variable names with neater descriptions and plot
        gather(key = key, value = Response, -individual_id, -primary_treatment, -event_name) %>%
        mutate(Response = factor(Response, levels = c("Not at All", "A Little", "Quite a Bit", "Very Much"))) %>%
        ## Optionally remove NAs, simply place '## dplyr...' if you wish to include NAs
        dplyr::filter(!is.na(Response)) %>%
        unique()
## Stacked bar-chart of domain responses using base ggplo2
ggplot(br23, aes(x = key, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "EORTC QLQ BR23 Domains at Baseline by Primary Treatment",
            subtitle = "Excludes Missing Responses") +
    facet_grid(~primary_treatment) +
    theme_bw()
## Same graphs using sjPlot::sjp.stackfrq(), plot by each treatment.
## To combine use something like cow_plot::plot_grid() / sjPlot::plot_grid() /
## patchwork (see https://github.com/thomasp85/patchwork)
br23_levels <- c("Not at All", "A Little", "Quite a Bit", "Very Much")
br23_adjuvant <- dplyr::filter(br23, primary_treatment == "Adjuvant Endocrine") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(br23_q31  = factor(br23_q31,  levels = br23_levels),
                        br23_q32  = factor(br23_q32,  levels = br23_levels),
                        br23_q33  = factor(br23_q33,  levels = br23_levels),
                        br23_q34  = factor(br23_q34,  levels = br23_levels),
                        br23_q35  = factor(br23_q35,  levels = br23_levels),
                        br23_q36  = factor(br23_q36,  levels = br23_levels),
                        br23_q37  = factor(br23_q37,  levels = br23_levels),
                        br23_q38  = factor(br23_q38,  levels = br23_levels),
                        br23_q39  = factor(br23_q39,  levels = br23_levels),
                        br23_q40  = factor(br23_q40,  levels = br23_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Adjuvant Endocrine",
                              prnt.plot = FALSE)
br23_primary <- dplyr::filter(br23, primary_treatment == "Primary Endocrine") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(br23_q31  = factor(br23_q31,  levels = br23_levels),
                        br23_q32  = factor(br23_q32,  levels = br23_levels),
                        br23_q33  = factor(br23_q33,  levels = br23_levels),
                        br23_q34  = factor(br23_q34,  levels = br23_levels),
                        br23_q35  = factor(br23_q35,  levels = br23_levels),
                        br23_q36  = factor(br23_q36,  levels = br23_levels),
                        br23_q37  = factor(br23_q37,  levels = br23_levels),
                        br23_q38  = factor(br23_q38,  levels = br23_levels),
                        br23_q39  = factor(br23_q39,  levels = br23_levels),
                        br23_q40  = factor(br23_q40,  levels = br23_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Primary Endocrine",
                              prnt.plot = FALSE)
br23_chemotherapy <- dplyr::filter(br23, primary_treatment == "Chemotherapy") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(br23_q31  = factor(br23_q31,  levels = br23_levels),
                        br23_q32  = factor(br23_q32,  levels = br23_levels),
                        br23_q33  = factor(br23_q33,  levels = br23_levels),
                        br23_q34  = factor(br23_q34,  levels = br23_levels),
                        br23_q35  = factor(br23_q35,  levels = br23_levels),
                        br23_q36  = factor(br23_q36,  levels = br23_levels),
                        br23_q37  = factor(br23_q37,  levels = br23_levels),
                        br23_q38  = factor(br23_q38,  levels = br23_levels),
                        br23_q39  = factor(br23_q39,  levels = br23_levels),
                        br23_q40  = factor(br23_q40,  levels = br23_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Chemotherapy",
                              prnt.plot = FALSE)
br23_radiotherapy <- dplyr::filter(br23, primary_treatment == "Radiotherapy") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(br23_q31  = factor(br23_q31,  levels = br23_levels),
                        br23_q32  = factor(br23_q32,  levels = br23_levels),
                        br23_q33  = factor(br23_q33,  levels = br23_levels),
                        br23_q34  = factor(br23_q34,  levels = br23_levels),
                        br23_q35  = factor(br23_q35,  levels = br23_levels),
                        br23_q36  = factor(br23_q36,  levels = br23_levels),
                        br23_q37  = factor(br23_q37,  levels = br23_levels),
                        br23_q38  = factor(br23_q38,  levels = br23_levels),
                        br23_q39  = factor(br23_q39,  levels = br23_levels),
                        br23_q40  = factor(br23_q40,  levels = br23_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Radiotherapy",
                              prnt.plot = FALSE)
br23_surgery <- dplyr::filter(br23, primary_treatment == "Surgery") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(br23_q31  = factor(br23_q31,  levels = br23_levels),
                        br23_q32  = factor(br23_q32,  levels = br23_levels),
                        br23_q33  = factor(br23_q33,  levels = br23_levels),
                        br23_q34  = factor(br23_q34,  levels = br23_levels),
                        br23_q35  = factor(br23_q35,  levels = br23_levels),
                        br23_q36  = factor(br23_q36,  levels = br23_levels),
                        br23_q37  = factor(br23_q37,  levels = br23_levels),
                        br23_q38  = factor(br23_q38,  levels = br23_levels),
                        br23_q39  = factor(br23_q39,  levels = br23_levels),
                        br23_q40  = factor(br23_q40,  levels = br23_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Surgery",
                              prnt.plot = FALSE)
br23_adjuvant$plot
br23_primary$plot
br23_chemotherapy$plot
br23_radiotherapy$plot
br23_surgery$plot

```

#### EORTC QLQ ELD15
```{r baseline_summary_demographics_eld15, echo = FALSE, cache = FALSE, fig.width = 8, fig.height = 8,eval = TRUE}
## Generate plots of ELD15 at Baseline...
##
## Histograms of scaled scores by treatment group
age_gap %>%
    ## Filter Baseline group, with primary_treatment defined and without missing or zero age
    dplyr::filter(event_name == "Baseline") %>%
    dplyr::filter(!is.na(primary_treatment)) %>%
    dplyr::select(individual_id,
                  primary_treatment,
                  mo_scale,
                  wao_scale,
                  wo_scale,
                  mp_scale,
                  boi_scale,
                  js_scale,
                  fs_scale) %>%
    gather(key   = Scale, value = value, -individual_id, -primary_treatment) %>%
    dplyr::filter(!is.na(value)) %>%
    mutate(Scale = gsub("_scale", "", Scale)) %>%
    unique() %>%
    ggplot(aes(value, fill = primary_treatment)) +
    geom_histogram(bins = 60) +
    xlab("EORTC QLQ ELD15") +
    ylab("N") +
    ggtitle(label = "EORTC QLQ ELD15 Scaled Scores by Primary Treatment Group",
            subtitle = "Y-axis varies between plots") +
    facet_grid(Scale~primary_treatment, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "none")
## Subset, reshape and tidy questionnaire responses...
eld15 <- age_gap %>%
        ## Filter Baseline group, with primary_treatment defined and without missing or zero age
        dplyr::filter(event_name == "Baseline") %>%
        dplyr::filter(!is.na(primary_treatment)) %>%
        ungroup() %>%
        dplyr::select(individual_id,
                      primary_treatment,
                      event_name,
                      eld15_q54, eld15_q55, eld15_q56, eld15_q57, eld15_q58,
                      eld15_q59, eld15_q60, eld15_q61, eld15_q62, eld15_q63,
                      eld15_q64, eld15_q65, eld15_q66, eld15_q67, eld15_q68) %>%
        ## Reshape the data, replace variable names with neater descriptions and plot
        gather(key = key, value = Response, -individual_id, -primary_treatment, -event_name) %>%
        mutate(Response = factor(Response, levels = c("Not at All", "A Little", "Quite a Bit", "Very Much"))) %>%
        ## Optionally remove NAs, simply place '## dplyr...' if you wish to include NAs
        dplyr::filter(!is.na(Response)) %>%
        unique()
## Stacked bar-chart of domain responses using base ggplo2
ggplot(eld15, aes(x = key, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "EORTC QLQ ELD15 Domains at Baseline by Primary Treatment",
            subtitle = "Excludes Missing Responses") +
    facet_grid(~primary_treatment) +
    theme_bw()
## Same graphs using sjPlot::sjp.stackfrq(), plot by each treatment.
## To combine use something like cow_plot::plot_grid() / sjPlot::plot_grid() /
## patchwork (see https://github.com/thomasp85/patchwork)
eld15_levels <- c("Not at All", "A Little", "Quite a Bit", "Very Much")
eld15_adjuvant <- dplyr::filter(eld15, primary_treatment == "Adjuvant Endocrine") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(eld15_q54  = factor(eld15_q54,  levels = eld15_levels),
                        eld15_q55  = factor(eld15_q55,  levels = eld15_levels),
                        eld15_q56  = factor(eld15_q56,  levels = eld15_levels),
                        eld15_q57  = factor(eld15_q57,  levels = eld15_levels),
                        eld15_q58  = factor(eld15_q58,  levels = eld15_levels),
                        eld15_q59  = factor(eld15_q59,  levels = eld15_levels),
                        eld15_q60  = factor(eld15_q60,  levels = eld15_levels),
                        eld15_q61  = factor(eld15_q61,  levels = eld15_levels),
                        eld15_q62  = factor(eld15_q62,  levels = eld15_levels),
                        eld15_q63  = factor(eld15_q63,  levels = eld15_levels),
                        eld15_q64  = factor(eld15_q64,  levels = eld15_levels),
                        eld15_q65  = factor(eld15_q65,  levels = eld15_levels),
                        eld15_q66  = factor(eld15_q66,  levels = eld15_levels),
                        eld15_q67  = factor(eld15_q67,  levels = eld15_levels),
                        eld15_q68  = factor(eld15_q68,  levels = eld15_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Adjuvant Endocrine",
                              prnt.plot = FALSE)
eld15_primary <- dplyr::filter(eld15, primary_treatment == "Primary Endocrine") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(eld15_q54  = factor(eld15_q54,  levels = eld15_levels),
                        eld15_q55  = factor(eld15_q55,  levels = eld15_levels),
                        eld15_q56  = factor(eld15_q56,  levels = eld15_levels),
                        eld15_q57  = factor(eld15_q57,  levels = eld15_levels),
                        eld15_q58  = factor(eld15_q58,  levels = eld15_levels),
                        eld15_q59  = factor(eld15_q59,  levels = eld15_levels),
                        eld15_q60  = factor(eld15_q60,  levels = eld15_levels),
                        eld15_q61  = factor(eld15_q61,  levels = eld15_levels),
                        eld15_q62  = factor(eld15_q62,  levels = eld15_levels),
                        eld15_q63  = factor(eld15_q63,  levels = eld15_levels),
                        eld15_q64  = factor(eld15_q64,  levels = eld15_levels),
                        eld15_q65  = factor(eld15_q65,  levels = eld15_levels),
                        eld15_q66  = factor(eld15_q66,  levels = eld15_levels),
                        eld15_q67  = factor(eld15_q67,  levels = eld15_levels),
                        eld15_q68  = factor(eld15_q68,  levels = eld15_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Primary Endocrine",
                              prnt.plot = FALSE)
eld15_chemotherapy <- dplyr::filter(eld15, primary_treatment == "Chemotherapy") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(eld15_q54  = factor(eld15_q54,  levels = eld15_levels),
                        eld15_q55  = factor(eld15_q55,  levels = eld15_levels),
                        eld15_q56  = factor(eld15_q56,  levels = eld15_levels),
                        eld15_q57  = factor(eld15_q57,  levels = eld15_levels),
                        eld15_q58  = factor(eld15_q58,  levels = eld15_levels),
                        eld15_q59  = factor(eld15_q59,  levels = eld15_levels),
                        eld15_q60  = factor(eld15_q60,  levels = eld15_levels),
                        eld15_q61  = factor(eld15_q61,  levels = eld15_levels),
                        eld15_q62  = factor(eld15_q62,  levels = eld15_levels),
                        eld15_q63  = factor(eld15_q63,  levels = eld15_levels),
                        eld15_q64  = factor(eld15_q64,  levels = eld15_levels),
                        eld15_q65  = factor(eld15_q65,  levels = eld15_levels),
                        eld15_q66  = factor(eld15_q66,  levels = eld15_levels),
                        eld15_q67  = factor(eld15_q67,  levels = eld15_levels),
                        eld15_q68  = factor(eld15_q68,  levels = eld15_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Chemotherapy",
                              prnt.plot = FALSE)
eld15_radiotherapy <- dplyr::filter(eld15, primary_treatment == "Radiotherapy") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(eld15_q54  = factor(eld15_q54,  levels = eld15_levels),
                        eld15_q55  = factor(eld15_q55,  levels = eld15_levels),
                        eld15_q56  = factor(eld15_q56,  levels = eld15_levels),
                        eld15_q57  = factor(eld15_q57,  levels = eld15_levels),
                        eld15_q58  = factor(eld15_q58,  levels = eld15_levels),
                        eld15_q59  = factor(eld15_q59,  levels = eld15_levels),
                        eld15_q60  = factor(eld15_q60,  levels = eld15_levels),
                        eld15_q61  = factor(eld15_q61,  levels = eld15_levels),
                        eld15_q62  = factor(eld15_q62,  levels = eld15_levels),
                        eld15_q63  = factor(eld15_q63,  levels = eld15_levels),
                        eld15_q64  = factor(eld15_q64,  levels = eld15_levels),
                        eld15_q65  = factor(eld15_q65,  levels = eld15_levels),
                        eld15_q66  = factor(eld15_q66,  levels = eld15_levels),
                        eld15_q67  = factor(eld15_q67,  levels = eld15_levels),
                        eld15_q68  = factor(eld15_q68,  levels = eld15_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Radiotherapy",
                              prnt.plot = FALSE)
eld15_surgery <- dplyr::filter(eld15, primary_treatment == "Surgery") %>%
                 dplyr::select(-primary_treatment, -event_name) %>%
                 spread(key, Response) %>%
                 mutate(eld15_q54  = factor(eld15_q54,  levels = eld15_levels),
                        eld15_q55  = factor(eld15_q55,  levels = eld15_levels),
                        eld15_q56  = factor(eld15_q56,  levels = eld15_levels),
                        eld15_q57  = factor(eld15_q57,  levels = eld15_levels),
                        eld15_q58  = factor(eld15_q58,  levels = eld15_levels),
                        eld15_q59  = factor(eld15_q59,  levels = eld15_levels),
                        eld15_q60  = factor(eld15_q60,  levels = eld15_levels),
                        eld15_q61  = factor(eld15_q61,  levels = eld15_levels),
                        eld15_q62  = factor(eld15_q62,  levels = eld15_levels),
                        eld15_q63  = factor(eld15_q63,  levels = eld15_levels),
                        eld15_q64  = factor(eld15_q64,  levels = eld15_levels),
                        eld15_q65  = factor(eld15_q65,  levels = eld15_levels),
                        eld15_q66  = factor(eld15_q66,  levels = eld15_levels),
                        eld15_q67  = factor(eld15_q67,  levels = eld15_levels),
                        eld15_q68  = factor(eld15_q68,  levels = eld15_levels)) %>%
                 dplyr::select(-individual_id) %>%
                 sjp.stackfrq(title = "Surgery",
                              prnt.plot = FALSE)
eld15_adjuvant$plot
eld15_primary$plot
eld15_chemotherapy$plot
eld15_radiotherapy$plot
eld15_surgery$plot

```

#### Barthel Activities of Daily Living
```{r baseline_summary_demographics_adl, echo = FALSE, cache = FALSE, fig.width = 8, fig.height = 8,eval = FALSE}
## Generate plots of ELD15 at Baseline...
##
## Histograms of scaled scores by treatment group
age_gap %>%
    ## Filter Baseline group, with primary_treatment defined and without missing or zero age
    dplyr::filter(event_name == "Baseline") %>%
    dplyr::filter(!is.na(primary_treatment)) %>%
    dplyr::select(individual_id,
                  primary_treatment,
                  adl_score) %>%
    gather(key   = Scale, value = value, -individual_id, -primary_treatment) %>%
    dplyr::filter(!is.na(value)) %>%
    mutate(Scale = gsub("_scale", "", Scale)) %>%
    unique() %>%
    ggplot(aes(value, fill = primary_treatment)) +
    geom_histogram(bins = 60) +
    xlab("ADL Score") +
    ylab("N") +
    ggtitle(label = "Barthel Activities of Daily Living Scores by Primary Treatment Group",
            subtitle = "Y-axis varies between plots") +
    facet_grid(Scale~primary_treatment, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "none")
## Subset, reshape and tidy questionnaire responses...
adl <- age_gap %>%
       ## Filter Baseline group, with primary_treatment defined and without missing or zero age
       dplyr::filter(event_name == "Baseline") %>%
       dplyr::filter(!is.na(primary_treatment)) %>%
       ungroup() %>%
       dplyr::select(individual_id,
                     primary_treatment,
                     event_name,
                     feeding, transfer_bed_chair, personal_toilet,
                     toiletting, bathing, walking_wheelchair, ascend_descend,
                     dressing, bowels, bladder) %>%
       unique()

## Stacked bar-chart of domain responses using base ggplo2
adl_plot <- list()
adl_plot$feeding <- adl %>%
    dplyr::filter(!is.na(feeding)) %>%
    mutate(Response = feeding) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Feeding") +
    theme_bw()
adl_plot$transfer_bed_chair <- adl %>%
    dplyr::filter(!is.na(transfer_bed_chair)) %>%
    mutate(Response = transfer_bed_chair) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Transfer Bed/Chair") +
    theme_bw()
adl_plot$personal_toilet <- adl %>%
    dplyr::filter(!is.na(personal_toilet)) %>%
    mutate(Response = personal_toilet) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Personal Toilet") +
    theme_bw()
adl_plot$toiletting <- adl %>%
    dplyr::filter(!is.na(toiletting)) %>%
    mutate(Response = toiletting) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "toiletting") +
    theme_bw()
adl_plot$bathing <- adl %>%
    dplyr::filter(!is.na(bathing)) %>%
    mutate(Response = bathing) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Bathing") +
    theme_bw()
adl_plot$walking_wheelchair <- adl %>%
    dplyr::filter(!is.na(walking_wheelchair)) %>%
    mutate(Response = walking_wheelchair) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Walking / Wheelchair") +
    theme_bw()
adl_plot$ascend_descend <- adl %>%
    dplyr::filter(!is.na(ascend_descend)) %>%
    mutate(Response = ascend_descend) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Ascend / Descend") +
    theme_bw()
adl_plot$dressing <- adl %>%
    dplyr::filter(!is.na(dressing)) %>%
    mutate(Response = dressing) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Dressing") +
    theme_bw()
adl_plot$bowels <- adl %>%
    dplyr::filter(!is.na(bowels)) %>%
    mutate(Response = bowels) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Bowels") +
    theme_bw()
adl_plot$bladder <- adl %>%
    dplyr::filter(!is.na(bladder)) %>%
    mutate(Response = bladder) %>%
    ggplot(aes(primary_treatment, fill = Response)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Bladder") +
    theme_bw()
## Combine all plots using patchworkm, forcing into two columns
adl_plot$feeding + adl_plot$transfer_bed_chair +
    adl_plot$personal_toilet + adl_plot$toiletting +
    adl_plot$bowels + adl_plot$bladder +
    adl_plot$bathing + adl_plot$walking_wheelchair +
    adl_plot$ascend_descend + adl_plot$dressing +
    plot_layout(ncol = 2)

## Same graphs using sjPlot::sjp.stackfrq(), plot by each treatment.
## To combine use something like cow_plot::plot_grid() / sjPlot::plot_grid() /
## patchwork (see https://github.com/thomasp85/patchwork)
adl_sjp <- list()
adl_sjp$feeding <- adl %>%
    dplyr::select(individual_id, primary_treatment, feeding) %>%
    spread(primary_treatment, feeding) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Feeding",
                 prnt.plot = FALSE)
adl_sjp$transfer_bed_chair <- adl %>%
    dplyr::select(individual_id, primary_treatment, transfer_bed_chair) %>%
    spread(primary_treatment, transfer_bed_chair) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Transfer Bed / Chair",
                 prnt.plot = FALSE)
adl_sjp$personal_toilet <- adl %>%
    dplyr::select(individual_id, primary_treatment, personal_toilet) %>%
    spread(primary_treatment, personal_toilet) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Personal Toilet",
                 prnt.plot = FALSE)
adl_sjp$toiletting <- adl %>%
    dplyr::select(individual_id, primary_treatment, toiletting) %>%
    spread(primary_treatment, toiletting) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Toiletting",
                 prnt.plot = FALSE)
adl_sjp$bowels <- adl %>%
    dplyr::select(individual_id, primary_treatment, bowels) %>%
    spread(primary_treatment, bowels) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Bowels",
                 prnt.plot = FALSE)
adl_sjp$bladder <- adl %>%
    dplyr::select(individual_id, primary_treatment, bladder) %>%
    spread(primary_treatment, bladder) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Bladder",
                 prnt.plot = FALSE)
adl_sjp$bathing <- adl %>%
    dplyr::select(individual_id, primary_treatment, bathing) %>%
    spread(primary_treatment, bathing) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Bathing",
                 prnt.plot = FALSE)
adl_sjp$walking_wheelchair <- adl %>%
    dplyr::select(individual_id, primary_treatment, walking_wheelchair) %>%
    spread(primary_treatment, walking_wheelchair) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Walking / Wheelchair",
                 prnt.plot = FALSE)
adl_sjp$ascend_descend <- adl %>%
    dplyr::select(individual_id, primary_treatment, ascend_descend) %>%
    spread(primary_treatment, ascend_descend) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Ascend / Descend",
                 prnt.plot = FALSE)
adl_sjp$dressing <- adl %>%
    dplyr::select(individual_id, primary_treatment, dressing) %>%
    spread(primary_treatment, dressing) %>%
    dplyr::select(-individual_id) %>%
    sjp.stackfrq(title     = "Dressing",
                 prnt.plot = FALSE)
adl_sjp$feeding
adl_sjp$transfer_bed_chair
adl_sjp$personal_toilet
adl_sjp$toiletting
adl_sjp$bowels
adl_sjp$bladder
adl_sjp$bathing
adl_sjp$walking_wheelchair
adl_sjp$ascend_descend
adl_sjp$dressing

```

#### Instrumental Activities of Daily Living
```{r baseline_summary_demographics_iadl, echo = FALSE, cache = FALSE, fig.width = 8, fig.height = 8,eval = TRUE}
## Generate plots of ELD15 at Baseline...
##
## Histograms of scaled scores by treatment group
age_gap %>%
    ## Filter Baseline group, with primary_treatment defined and without missing or zero age
    dplyr::filter(event_name == "Baseline") %>%
    dplyr::filter(!is.na(primary_treatment)) %>%
    dplyr::select(individual_id,
                  primary_treatment,
                  iadl_score) %>%
    gather(key   = Scale, value = value, -individual_id, -primary_treatment) %>%
    dplyr::filter(!is.na(value)) %>%
    mutate(Scale = gsub("_scale", "", Scale)) %>%
    unique() %>%
    ggplot(aes(value, fill = primary_treatment)) +
    geom_histogram(bins = 60) +
    xlab("ADL Score") +
    ylab("N") +
    ggtitle(label = "Instrumental Activities of Daily Living Scores by Primary Treatment Group",
            subtitle = "Y-axis varies between plots") +
    facet_grid(Scale~primary_treatment, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "none")
## Subset, reshape and tidy questionnaire responses...
iadl <- age_gap %>%
        ## Filter Baseline group, with primary_treatment defined and without missing or zero age
        dplyr::filter(event_name == "Baseline") %>%
        dplyr::filter(!is.na(primary_treatment)) %>%
        ungroup() %>%
        dplyr::select(individual_id,
                      primary_treatment,
                      event_name,
                      telephone, shopping, food_prep, housekeeping, laundry,
                      transport, medication, finances)
        unique()
## Stacked bar-chart of domain responses using base ggplot2.opts
## Because the responses are not consistent across questions these are plotted indivudally
## and then combined into one plot
iadl_plots <- list()
iadl_plots$feeding <- adl %>%
    dplyr::filter(!is.na(feeding)) %>%
    ggplot(aes(x = feeding)) +
    geom_bar(position = "fill") +
    coord_flip() +
    xlab("") +
    ylab("Proportion") +
    ggtitle(label = "Instrumental Activities of Daily Living Domains at Baseline by Primary Treatment",
            subtitle = "Excludes Missing Responses") +
    facet_grid(~primary_treatment) +
    theme_bw()
## ## Same graphs using sjPlot::sjp.stackfrq(), plot by each treatment.
## ## To combine use something like cow_plot::plot_grid() / sjPlot::plot_grid() /
## ## patchwork (see https://github.com/thomasp85/patchwork)
## adl_levels <- c("Not at All", "A Little", "Quite a Bit", "Very Much")
## adl_adjuvant <- dplyr::filter(adl, primary_treatment == "Adjuvant Endocrine") %>%
##                  dplyr::select(-primary_treatment, -event_name) %>%
##                  spread(key, Response) %>%
##                  mutate(adl_q54  = factor(adl_q54,  levels = adl_levels),
##                         adl_q55  = factor(adl_q55,  levels = adl_levels),
##                         adl_q56  = factor(adl_q56,  levels = adl_levels),
##                         adl_q57  = factor(adl_q57,  levels = adl_levels),
##                         adl_q58  = factor(adl_q58,  levels = adl_levels),
##                         adl_q59  = factor(adl_q59,  levels = adl_levels),
##                         adl_q60  = factor(adl_q60,  levels = adl_levels),
##                         adl_q61  = factor(adl_q61,  levels = adl_levels),
##                         adl_q62  = factor(adl_q62,  levels = adl_levels),
##                         adl_q63  = factor(adl_q63,  levels = adl_levels),
##                         adl_q64  = factor(adl_q64,  levels = adl_levels),
##                         adl_q65  = factor(adl_q65,  levels = adl_levels),
##                         adl_q66  = factor(adl_q66,  levels = adl_levels),
##                         adl_q67  = factor(adl_q67,  levels = adl_levels),
##                         adl_q68  = factor(adl_q68,  levels = adl_levels)) %>%
##                  dplyr::select(-individual_id) %>%
##                  sjp.stackfrq(title = "Adjuvant Endocrine",
##                               prnt.plot = FALSE)
## adl_primary <- dplyr::filter(adl, primary_treatment == "Primary Endocrine") %>%
##                  dplyr::select(-primary_treatment, -event_name) %>%
##                  spread(key, Response) %>%
##                  mutate(adl_q54  = factor(adl_q54,  levels = adl_levels),
##                         adl_q55  = factor(adl_q55,  levels = adl_levels),
##                         adl_q56  = factor(adl_q56,  levels = adl_levels),
##                         adl_q57  = factor(adl_q57,  levels = adl_levels),
##                         adl_q58  = factor(adl_q58,  levels = adl_levels),
##                         adl_q59  = factor(adl_q59,  levels = adl_levels),
##                         adl_q60  = factor(adl_q60,  levels = adl_levels),
##                         adl_q61  = factor(adl_q61,  levels = adl_levels),
##                         adl_q62  = factor(adl_q62,  levels = adl_levels),
##                         adl_q63  = factor(adl_q63,  levels = adl_levels),
##                         adl_q64  = factor(adl_q64,  levels = adl_levels),
##                         adl_q65  = factor(adl_q65,  levels = adl_levels),
##                         adl_q66  = factor(adl_q66,  levels = adl_levels),
##                         adl_q67  = factor(adl_q67,  levels = adl_levels),
##                         adl_q68  = factor(adl_q68,  levels = adl_levels)) %>%
##                  dplyr::select(-individual_id) %>%
##                  sjp.stackfrq(title = "Primary Endocrine",
##                               prnt.plot = FALSE)
## adl_chemotherapy <- dplyr::filter(adl, primary_treatment == "Chemotherapy") %>%
##                  dplyr::select(-primary_treatment, -event_name) %>%
##                  spread(key, Response) %>%
##                  mutate(adl_q54  = factor(adl_q54,  levels = adl_levels),
##                         adl_q55  = factor(adl_q55,  levels = adl_levels),
##                         adl_q56  = factor(adl_q56,  levels = adl_levels),
##                         adl_q57  = factor(adl_q57,  levels = adl_levels),
##                         adl_q58  = factor(adl_q58,  levels = adl_levels),
##                         adl_q59  = factor(adl_q59,  levels = adl_levels),
##                         adl_q60  = factor(adl_q60,  levels = adl_levels),
##                         adl_q61  = factor(adl_q61,  levels = adl_levels),
##                         adl_q62  = factor(adl_q62,  levels = adl_levels),
##                         adl_q63  = factor(adl_q63,  levels = adl_levels),
##                         adl_q64  = factor(adl_q64,  levels = adl_levels),
##                         adl_q65  = factor(adl_q65,  levels = adl_levels),
##                         adl_q66  = factor(adl_q66,  levels = adl_levels),
##                         adl_q67  = factor(adl_q67,  levels = adl_levels),
##                         adl_q68  = factor(adl_q68,  levels = adl_levels)) %>%
##                  dplyr::select(-individual_id) %>%
##                  sjp.stackfrq(title = "Chemotherapy",
##                               prnt.plot = FALSE)
## adl_radiotherapy <- dplyr::filter(adl, primary_treatment == "Radiotherapy") %>%
##                  dplyr::select(-primary_treatment, -event_name) %>%
##                  spread(key, Response) %>%
##                  mutate(adl_q54  = factor(adl_q54,  levels = adl_levels),
##                         adl_q55  = factor(adl_q55,  levels = adl_levels),
##                         adl_q56  = factor(adl_q56,  levels = adl_levels),
##                         adl_q57  = factor(adl_q57,  levels = adl_levels),
##                         adl_q58  = factor(adl_q58,  levels = adl_levels),
##                         adl_q59  = factor(adl_q59,  levels = adl_levels),
##                         adl_q60  = factor(adl_q60,  levels = adl_levels),
##                         adl_q61  = factor(adl_q61,  levels = adl_levels),
##                         adl_q62  = factor(adl_q62,  levels = adl_levels),
##                         adl_q63  = factor(adl_q63,  levels = adl_levels),
##                         adl_q64  = factor(adl_q64,  levels = adl_levels),
##                         adl_q65  = factor(adl_q65,  levels = adl_levels),
##                         adl_q66  = factor(adl_q66,  levels = adl_levels),
##                         adl_q67  = factor(adl_q67,  levels = adl_levels),
##                         adl_q68  = factor(adl_q68,  levels = adl_levels)) %>%
##                  dplyr::select(-individual_id) %>%
##                  sjp.stackfrq(title = "Radiotherapy",
##                               prnt.plot = FALSE)
## adl_surgery <- dplyr::filter(adl, primary_treatment == "Surgery") %>%
##                  dplyr::select(-primary_treatment, -event_name) %>%
##                  spread(key, Response) %>%
##                  mutate(adl_q54  = factor(adl_q54,  levels = adl_levels),
##                         adl_q55  = factor(adl_q55,  levels = adl_levels),
##                         adl_q56  = factor(adl_q56,  levels = adl_levels),
##                         adl_q57  = factor(adl_q57,  levels = adl_levels),
##                         adl_q58  = factor(adl_q58,  levels = adl_levels),
##                         adl_q59  = factor(adl_q59,  levels = adl_levels),
##                         adl_q60  = factor(adl_q60,  levels = adl_levels),
##                         adl_q61  = factor(adl_q61,  levels = adl_levels),
##                         adl_q62  = factor(adl_q62,  levels = adl_levels),
##                         adl_q63  = factor(adl_q63,  levels = adl_levels),
##                         adl_q64  = factor(adl_q64,  levels = adl_levels),
##                         adl_q65  = factor(adl_q65,  levels = adl_levels),
##                         adl_q66  = factor(adl_q66,  levels = adl_levels),
##                         adl_q67  = factor(adl_q67,  levels = adl_levels),
##                         adl_q68  = factor(adl_q68,  levels = adl_levels)) %>%
##                  dplyr::select(-individual_id) %>%
##                  sjp.stackfrq(title = "Surgery",
##                               prnt.plot = FALSE)
## adl_adjuvant$plot
## adl_primary$plot
## adl_chemotherapy$plot
## adl_radiotherapy$plot
## adl_surgery$plot

```
