# Introduction

As of writing the planned five year survival data from [NHS Digital](https://digital.nhs.uk/).  The [Bridging the Age Gap](https://www.sheffield.ac.uk/oncology-metabolism/research/surgicaloncology/research/agegap) Chief Investigator, [Lynda Wyld](mailto:l.wyld@sheffield.ac.uk) wrote to Terry Hill (NHS Digital Data Dissemination Director) who sits on the [Research Advisory Group](https://digital.nhs.uk/research-advisory-group) on 2017-10-23 to appeal the decision by NHS Digital to refuse access to the data.  As of writing `r date()` no response has been seen the the author.

This means the primary outcome of the cohort study, comparing five-year survival rates between different primary treatment groups, is somewhat problematic.  Possible options include...

* Using two-year survival rates captured on the Study Completion and Discontinuation Case Report Forms.
* Returning to centers and reviewing all case notes for participants to obtain data on survivorship at five-year follow-up.

The later option will take considerable time and the data is not currently available.  In the mean time the available Study Completion data has been investigated to look at its utility for answering the question of how two-year survival rates compare between different primary treatment arms.

**Caveat** The Case Report Forms for this study only capture accurately the dates of surgery.  Follow-ups at six-weeks, six, twelve, eighteen and 24 months whilst capturing the treatment received since last contact, do not record the date of those treatments, they are instead recorded with the date of the follow-up.  This means that it is not straight-forward to determine the primary treatment participants of the study have received.  In consultation with Lynda Wyld an algorithm for defining these has been determined but it still leaves some ~400 participants with unusual treatment profiles whose data is pending review by Lynda for classification (data was provided 2017-11-21).
