## Methods

The data was extracted from the [Prospect Database](https://www.ctru-prospect.shef.ac.uk) on 2018-01-30 and data from the 54 individual text files (one for each Case Report Form (CRF)) combined in the statistical programming language [R](https://www.r-project.org/).  A number of variables are derived by Prospect for scoring the various questionnaires and further reconcilation of data recorded on both body axes (i.e. left and right side) is performed when combining the files (although since this is not the focus of the current report no further discussion will be made of this).

### Baseline Characteristics

A multitude of baseline characteristics are summarised and reported for each of the treatment groups.  No formal test for statistically significant differences between these are made as it is not recommended **TODO** Senn citation on differences at baseline?

### Primary Treatment

As alluded to in the Introduction the allocation of individuals to primary treatment has not been straight-forward.  Based on clinical knowledge of treatment pathways provided by Lynda Wyld (meeting held 2017-10-23 09:00-11:00) notes were taken a hand-sketched schematic produced (see [this document](https://docs.google.com/document/d/1xSykX3mYtWoFng3gmf05Xjk7OX5WtfqV2RyRyvvvAcs/edit?usp=sharing) pg5-6, ignore table on pg4-5 which was not completed).  These have guided the implementation of an algorithm for classifying treatment as described below.

The algorithm, the term used for a set of rules which in this case are implemented in the programming language [R](https://www.r-project.org/) since the derivation of this is done *after* exporting the data from the [Prospect](https://www.ctru-prospect.shef.ac.uk/) database are described below.  It uses a series of `if (...) else if(...)` statements and as such the first condition that is met determines the Primary Treatment an individual is allocated to.  If none of the conditions are met then the Primary Treatment is missing and requires review.

    IF(endocrine_therapy == 'Yes' AND primary_adjuvant == 'Primary'  THEN 'Primary Endocrine')
    ELSE IF(endocrine_therapy == 'Yes' AND primary_adjuvant == 'Adjuvant' THEN 'Adjuvant Endocrine')
    ELSE IF(surgery == 'Yes' AND primary_adjuvant == 'Adjuvant' THEN 'Surgery')
    ELSE IF(surgery == 'Yes' AND primary_adjuvant == 'Neoddjuvant' THEN 'Surgery')
    ELSE IF(surgery == 'Yes' AND primary_adjuvant == '' THEN 'Surgery')
    ELSE IF(endocrine_therapy == 'No' AND surgery == 'No' AND chemotherapy == 'Yes' THEN 'Chemotherapy')
    ELSE IF(endocrine_therapy == 'No' AND surgery == 'No' AND chemotherapy == 'No' AND radiotherapy == 'Yes' THEN 'Radiotherapy')
    ELSE IF(trastuzumab == 'Yes' THEN Trastuzumab')


The terms to the left of the `==` are variables as described below...

| Variable | Description | Case Report Form |
|:---------|:------------|:-----------------|
| `endocrine_therapy` | Indicator of Endocrine Therapy being received | `Therapy Assessment` |
| `surgery` | Indicator of Surgery being received | `Therapy Assessment` |
| `chemotherapy` | Indicator of Chemotherapy being received | `Therapy Assessment` |
| `radiotherapy` | Indicator of Radiotherapy being received | `Therapy Assessment` |
| `trastuzumab` | Indicator of Trastuzumab being received | `Therapy Assessment` |
| `primary_adjuvant` | Indicator of the type of `endocrine_therapy` received | `Endocrine Therapy` |


Data on individuals who could not be classified was provided to Lynda Wyld 2017-11-21 (see email from [n.shephard@sheffield.ac.uk](mailto:n.shephard@sheffield.ac.uk) @ 16:40 **Subject** [AGEGAP] Data for review) for review and classification to Primarty Treatment

**NB** If this is not available, as is the case at the time of writing, then such individuals will in essence be excluded from all analyses as they can not unequivocally be allocated to a primary treatment group, although the option to include them as a group of their own under the category of `Other` exists.

### Death Follow-up

The following fields from the `Study Completion and Discontinuation Form` CRF are merged into the combined data set.  The date on which the `Study Completion and Discontinuation Form `is completed is required because it does not always align with the two-year follow-up (see results).

| Field      | Description       |
|:-----------|:------------------|
| `study_completiong_dt`        | Date Study Completion form completed. Date not always on 24 month follow-up, even if study completed.    |
| `disc_rsn` | Reason for discontinuation. |
| `disc_death_dt` | Date of death if participant died. |
| `death_cause_1` | Primary cause of death. |
| `death_cause_2` | Secondary cause of death. |
| `death_cause_3` | Tertiary cause of death. |

#### Comparison of Survival

[Kaplan-Meier]() plots will be generated to provide a graphical overview and crude unadjusted estimate of survivorship by treatment allocation.
