#### Event
```{r results_missing_patterns_radiotherapy_event, echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(individual_id, event_name, site, which_breast_right_radio, which_breast_left_radio, r_site_breast, r_site_axilla, r_site_supraclavicular, r_site_chest_wall, r_site_other, r_breast_fractions, r_axilla_fractions, r_supra_fractions, r_chest_fractions, r_other_fractions, r_radiotherapy_aes, l_site_breast, l_site_axilla, l_site_supraclavicular, l_site_chest_wall, l_site_other, l_breast_fractions, l_axilla_fractions, l_supra_fractions, l_chest_fractions, l_other_fractions, l_radiotherapy_aes, r_skin_erythema, r_pain, r_breast_oedema, r_breast_shrink, r_breast_pain, l_skin_erythema, l_pain, l_breast_oedema, l_breast_shrink, l_breast_pain) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
t <- left_join(t,
               master$lookups_fields) %>%
     ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
     geom_raster() +
     facet_grid(event_name~., scales = 'free_y') +
     theme_bw() +
     theme(axis.text.x = element_text(angle = 90))
t
## Plot using ggplotly
## ggplotly(t)


```

#### Site
```{r results_missing_patterns_radiotherapy_site, echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(individual_id, event_name, site, which_breast_right_radio, which_breast_left_radio, r_site_breast, r_site_axilla, r_site_supraclavicular, r_site_chest_wall, r_site_other, r_breast_fractions, r_axilla_fractions, r_supra_fractions, r_chest_fractions, r_other_fractions, r_radiotherapy_aes, l_site_breast, l_site_axilla, l_site_supraclavicular, l_site_chest_wall, l_site_other, l_breast_fractions, l_axilla_fractions, l_supra_fractions, l_chest_fractions, l_other_fractions, l_radiotherapy_aes, r_skin_erythema, r_pain, r_breast_oedema, r_breast_shrink, r_breast_pain, l_skin_erythema, l_pain, l_breast_oedema, l_breast_shrink, l_breast_pain) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
t <- left_join(t,
               master$lookups_fields) %>%
     ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
     geom_raster() +
     facet_grid(site~., scales = 'free_y') +
     theme_bw() +
     theme(axis.text.x = element_text(angle = 90))
t
## Plot using ggplotly
## ggplotly(t)


```


#### Event and Site
```{r results_missing_patterns_radiotherapy_event_site, echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(individual_id, event_name, site, which_breast_right_radio, which_breast_left_radio, r_site_breast, r_site_axilla, r_site_supraclavicular, r_site_chest_wall, r_site_other, r_breast_fractions, r_axilla_fractions, r_supra_fractions, r_chest_fractions, r_other_fractions, r_radiotherapy_aes, l_site_breast, l_site_axilla, l_site_supraclavicular, l_site_chest_wall, l_site_other, l_breast_fractions, l_axilla_fractions, l_supra_fractions, l_chest_fractions, l_other_fractions, l_radiotherapy_aes, r_skin_erythema, r_pain, r_breast_oedema, r_breast_shrink, r_breast_pain, l_skin_erythema, l_pain, l_breast_oedema, l_breast_shrink, l_breast_pain) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
t <- left_join(t,
               master$lookups_fields) %>%
     ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
     geom_raster() +
     facet_grid(site~event_name, scales = 'free_y') +
     theme_bw() +
     theme(axis.text.x = element_text(angle = 90))
t
## Plot using ggplotly
## ggplotly(t)

```
