#### Event and Site
```{r results_missing_patterns_template_event_site, , echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(TEMPLATE) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
left_join(t,
          master$lookups_fields) %>%
    ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
    geom_raster() +
    facet_grid(site~event_name, scales = 'free_y') +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90)) %>%
    ggplotly()

```

#### Event
```{r results_missing_patterns_template_event, , echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(TEMPLATE) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
left_join(t,
          master$lookups_fields) %>%
    ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
    geom_raster() +
    facet_grid(event_name~., scales = 'free_y') +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90)) %>%
    ggplotly()


```

#### Site
```{r results_missing_patterns_template_site, , echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(TEMPLATE) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
left_join(t,
          master$lookups_fields) %>%
    ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
    geom_raster() +
    facet_grid(site~., scales = 'free_y') +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90)) %>%
    ggplotly()


```
