#### Event
```{r results_missing_patterns_surgery_event, echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(individual_id, event_name, site, general_local, which_breast_right_surgery, which_breast_left_surgery, r_surgery_type, r_axillary_type, r_surgery_aes_acute, r_sa_haemorrhage, r_sa_seroma, r_sa_haematoma, r_sa_infection, r_sa_necrosis, r_sa_wound, r_surgery_aes_chronic, r_sc_wound_pain, r_sc_functional_diff, r_sc_neuropathy, r_sc_lymphoedema, r_tumour_size, r_allred, r_h_score, r_her_2_score, r_onco_offered, r_onco_used, r_risk_score, r_tumour_type, r_tumour_grade, r_margins_clear, r_margin, r_designation_anterior, r_designation_posterior, r_designation_lateral, r_designation_medial, r_designation_superior, r_designation_inferior, r_close_margin, r_nodes_excised, r_nodes_involved, l_surgery_type, l_axillary_type, l_surgery_aes_acute, l_sa_haemorrhage, l_sa_seroma, l_sa_haematoma, l_sa_infection, l_sa_necrosis, l_sa_wound, l_surgery_aes_chronic, l_sc_wound_pain, l_sc_functional_diff, l_sc_neuropathy, l_sc_lymphoedema, l_tumour_size, l_allred, l_h_score, l_her_2_score, l_onco_offered, l_onco_used, l_risk_score, l_tumour_type, l_tumour_grade, l_margins_clear, l_margin, l_designation_anterior, l_designation_posterior, l_designation_lateral, l_designation_medial, l_designation_superior, l_designation_inferior, l_close_margin, l_nodes_excised, l_nodes_involved) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
t <- left_join(t,
               master$lookups_fields) %>%
     ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
     geom_raster() +
     facet_grid(event_name~., scales = 'free_y') +
     theme_bw() +
     theme(axis.text.x = element_text(angle = 90))
t
## Plot using ggplotly
## ggplotly(t)


```

#### Site
```{r results_missing_patterns_surgery_site, echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(individual_id, event_name, site, general_local, which_breast_right_surgery, which_breast_left_surgery, r_surgery_type, r_axillary_type, r_surgery_aes_acute, r_sa_haemorrhage, r_sa_seroma, r_sa_haematoma, r_sa_infection, r_sa_necrosis, r_sa_wound, r_surgery_aes_chronic, r_sc_wound_pain, r_sc_functional_diff, r_sc_neuropathy, r_sc_lymphoedema, r_tumour_size, r_allred, r_h_score, r_her_2_score, r_onco_offered, r_onco_used, r_risk_score, r_tumour_type, r_tumour_grade, r_margins_clear, r_margin, r_designation_anterior, r_designation_posterior, r_designation_lateral, r_designation_medial, r_designation_superior, r_designation_inferior, r_close_margin, r_nodes_excised, r_nodes_involved, l_surgery_type, l_axillary_type, l_surgery_aes_acute, l_sa_haemorrhage, l_sa_seroma, l_sa_haematoma, l_sa_infection, l_sa_necrosis, l_sa_wound, l_surgery_aes_chronic, l_sc_wound_pain, l_sc_functional_diff, l_sc_neuropathy, l_sc_lymphoedema, l_tumour_size, l_allred, l_h_score, l_her_2_score, l_onco_offered, l_onco_used, l_risk_score, l_tumour_type, l_tumour_grade, l_margins_clear, l_margin, l_designation_anterior, l_designation_posterior, l_designation_lateral, l_designation_medial, l_designation_superior, l_designation_inferior, l_close_margin, l_nodes_excised, l_nodes_involved) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
t <- left_join(t,
               master$lookups_fields) %>%
     ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
     geom_raster() +
     facet_grid(site~., scales = 'free_y') +
     theme_bw() +
     theme(axis.text.x = element_text(angle = 90))
t
## Plot using ggplotly
## ggplotly(t)


```


#### Event and Site
```{r results_missing_patterns_surgery_event_site, echo = FALSE, warning = FALSE, message = FALSE, results = 'show', cache = FALSE, fig_width = 10, fig_height = 20, eval = TRUE}
t <- age_gap %>%
     dplyr::select(individual_id, event_name, site, general_local, which_breast_right_surgery, which_breast_left_surgery, r_surgery_type, r_axillary_type, r_surgery_aes_acute, r_sa_haemorrhage, r_sa_seroma, r_sa_haematoma, r_sa_infection, r_sa_necrosis, r_sa_wound, r_surgery_aes_chronic, r_sc_wound_pain, r_sc_functional_diff, r_sc_neuropathy, r_sc_lymphoedema, r_tumour_size, r_allred, r_h_score, r_her_2_score, r_onco_offered, r_onco_used, r_risk_score, r_tumour_type, r_tumour_grade, r_margins_clear, r_margin, r_designation_anterior, r_designation_posterior, r_designation_lateral, r_designation_medial, r_designation_superior, r_designation_inferior, r_close_margin, r_nodes_excised, r_nodes_involved, l_surgery_type, l_axillary_type, l_surgery_aes_acute, l_sa_haemorrhage, l_sa_seroma, l_sa_haematoma, l_sa_infection, l_sa_necrosis, l_sa_wound, l_surgery_aes_chronic, l_sc_wound_pain, l_sc_functional_diff, l_sc_neuropathy, l_sc_lymphoedema, l_tumour_size, l_allred, l_h_score, l_her_2_score, l_onco_offered, l_onco_used, l_risk_score, l_tumour_type, l_tumour_grade, l_margins_clear, l_margin, l_designation_anterior, l_designation_posterior, l_designation_lateral, l_designation_medial, l_designation_superior, l_designation_inferior, l_close_margin, l_nodes_excised, l_nodes_involved) %>%
     gather(key = identifier, value = value, -individual_id, -event_name, -site) %>%
     mutate(Missing = is.na(value),
            individual_id = factor(individual_id)) %>%
     dplyr::filter(event_name != 'Surgery')
t <- left_join(t,
               master$lookups_fields) %>%
     ggplot(., aes(x = label, y = individual_id, fill = Missing)) +
     geom_raster() +
     facet_grid(site~event_name, scales = 'free_y') +
     theme_bw() +
     theme(axis.text.x = element_text(angle = 90))
t
## Plot using ggplotly
## ggplotly(t)

```
