---
site: blogdown:::blogdown_site
---

Bridging the Age-Gap in Breast Cancer seeks to improve outcomes for older women diagnosed with breast cancer.  It is registered with the [ISCRTN](http://www.isrctn.com/) under study [ISRCTN46099296 (DOI 10.1186/ISRCTN46099296)](http://www.isrctn.com/ISRCTN46099296) and is a collaboration between researchers at [The University of Sheffield](https://www.sheffield.ac.uk/oncology-metabolism/research/surgicaloncology/research/agegap), [Sheffield Hallam University](https://www.shu.ac.uk/research/specialisms/centre-for-health-and-social-care-research/what-we-do/our-expertise/health-care-and-service-delivery-research/case-studies/bridging-the-age-gap-in-breast-cancer-research-improving-outcomes-for-older-women) and the participating NHS Trusts.  The study is co-ordinated, run and managed by the [Sheffield Clinical Trials Research Unit (CTRU)](https://www.sheffield.ac.uk/scharr/sections/dts/ctru), who provide study management, data capture and management and statistical analysis.


# Outcome Measures

The primary outcome is the EORTC-QLQ-C30 generic Quality of Life questionnaire measured at 6 months post-intervention.  There are multiple secondary outcomes, which are listed along with the primary in the table below

| Questionnaire   | Description                                         | Assesed at... | Citation            |
|-----------------|-----------------------------------------------------|---------------|---------------------|
| EORTC-QLQ-C30   | General quality of life survey for clinical trials. | 6 months      | @aaronson1993       |
| EORTC-QLQ-BR23  | Breast Cancer specific quality of life survey.      | 6 months      | @sprangers1996      |
| EORTC-QLQ-ELD15 | Older person specific quality of life survey.       | 6 months      | @johnson2010        |
| Decision Regret Scale | Assessing regret of decisions                 | 6 weeks / 6 months | @brehaut2003   |
| CollaboRATE     | Shared decision making assessment                   | Baseline      | @barr2014           |
| Spielberger State Anxiety Inventory | Assesses patienty anxsieety levels| 6 weeks / 6 months | @marteau1992 |
| Non-validated   | Assessment of knowledge, readiness to decide and treatment preference | baseline | NA     |
| Brief Illness Perceptions | Assess patients view of their illness     | 6 weeks / 6 months | @broadbent2006 |
| Brief COPE      | Coping assessment                                   | 6 weeks / 6 months | @carver1997    |
| Survival        | Survival outcomes from breast cancer                | 6 months      | @bradburn2003b      |

# Subrgoup Analysis

A number of subgroup analyses have been pre-specified, despite the reduced power such groups will have for detecting the specified minimal clinical effect, and are detailed in the table below.

| Subgroup           | Outcome                  |
|--------------------|--------------------------|
| Age 75-79          | EORTC-QLQ-C30 @ 6 months |
| Age 80-84          | EORTC-QLQ-C30 @ 6 months |
| Age 85-89          | EORTC-QLQ-C30 @ 6 months |
| Age 90+            | EORTC-QLQ-C30 @ 6 months |
| Charlson Score     | EORTC-QLQ-C30 @ 6 months |
| Barthel Index      | EORTC-QLQ-C30 @ 6 months |
| Degree of Dementia | EORTC-QLQ-C30 @ 6 months |
