---
title: Bridging the Age Gap in Elderly Women with Breast Cancer
output: word_document
bibliography: ../sections/bibliography.bib
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE, results = 'hide', cache = FALSE, eval = TRUE}
library(agegap)
##opts_chunk$set(dev = 'pdf')
opts_chunk$set(cache.path = 'cache/',
               width    = 200,
               fig.height = 8,
               fig.width  = 8,
               warning = FALSE,
               message = FALSE)
options(digits = 3,
        imputations = 5)
## Ensure anchors are assessed first
## opts_knit$set(eval.after = 'echo')
## Hooks
## knit_hooks$set(anchor = hook_anchor)
## Set a seed
set.seed(69027181)
## Set sensible defaults
ggplot2.opts <- list()
ggplot2.opts$binwidth <- 30
## Exclusions
##
## The following 'non-recruited' need excluding from all analyses
## exclusions <- c()

```

A number of queries need addressing in order for Statistics to progress with producing summary tables, figures and statistical analyses.  These are detailed in the sections that follow.

## Statistical Analysis Plans  {.tabset .tabset-fade .tabset-pills}
```{r child = '2017-08-21_post_meeting/statistical_analysis_plan.Rmd', eval = TRUE}
```


## Treatment Profiles {.tabset .tabset-fade .tabset-pills}
```{r child = '2017-08-21_post_meeting/treatment_profiles.Rmd', eval = TRUE}
```


## References

<!-- # References -->
