---
title: Survival and Deaths in the Bridging The Age Gap Study
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: bibliography.bib
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE, results = 'hide', cache = FALSE, eval = TRUE}
library(agegap)
library(sjPlot)
library(patchwork)
##opts_chunk$set(dev = 'pdf')
opts_chunk$set(cache.path = 'cache/',
               width    = 200,
               fig.height = 8,
               fig.width  = 8,
               warning = FALSE,
               message = FALSE)
options(digits = 3,
        imputations = 5)
## Ensure anchors are assessed first
## opts_knit$set(eval.after = 'echo')
## Hooks
## knit_hooks$set(anchor = hook_anchor)
## Set a seed
set.seed(69027181)
## Set sensible defaults
ggplot2.opts <- list()
ggplot2.opts$binwidth <- 30
## Exclusions
##
## The following 'non-recruited' need excluding from all analyses
## exclusions <- c()

```

```{r child='survival/intro.Rmd', eval = TRUE}
```

```{r child='survival/methods.Rmd', eval = TRUE}
```

```{r child='survival/results.Rmd', eval = TRUE}
```


```{r child='survival/appendix.Rmd', eval = TRUE}
```

## References
