# Introduction
Each year in the UK 16,000 women over the age of 70 develop breast cancer.  Breast cancer specific survival rates for women in this age group are inferior to those of younger women.  This may reflect later stage at presentation due to lack of screening and reduced breast awareness.  It may also reflect adverse cancer outcomes due to sub-optimal age and frailty stratified treatment protocols (such as omission of surgery, chemotherapy, radiotherapy or trastuzumab) implemented to avoid toxicity.   Fitness and frailty adjusted protocols may be appropriate in some circumstances but may compromise disease specific and disease free survival rates.   The Bridging the Age Gap in Breast Cancer trial is a comprehensive cohort study to explore the selection criteria and age, fitness, frailty and disease stratified outcomes from early breast cancer in older UK women.  A particularly prevalent treatment strategy, for women with oestrogen sensitive breast cancer, is the omission of surgery and the sole use of antioestrogen drugs.  This is called primary endocrine therapy and was first reported nearly 40 years ago.   In the UK, up to 40% of older women do not have surgery for their primary, operable breast cancer.  This type of therapeutic strategy is ideal for women with strongly oestrogen sensitive breast cancer, who are likely to have a life expectancy of less than 3-5 years (due to age, frailty or ill health) or those for whom surgery would be associated with unacceptable risks.   Patient preference is also an important consideration.   Unfortunately there is evidence that the selection criteria used are highly heterogeneous with some surgeons rarely offering PET, even to the frailest women and others offering PET to those whose predicted life expectancy is in excess of 10 years.    Randomised trials and cohort study data show that PET is associated with inferior rates of local disease control and reduced disease specific survival rates and hence this may be a factor contributing to inferior outcomes in older women.


This paper reports the selection criteria used by UK breast surgeons and oncologists and early survival outcomes when deciding between surgery or primary endocrine therapy in women with oestrogen sensitive breast cancer.
